version: '3.0'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  # server:
  #   stdin_open: true
  #   image: clue/json-server
  #   ports:
  #     - '3100:80'
  #   volumes:
  #     - './server/db.json:/data/db.json'
